# Site settings
title: Fusepool P3
email: p3-dev@netlabs.org
description: > # this means to ignore newlines until "baseurl:"
  Fusepool P3 makes it easy to process data and publish it as linked data.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fusepoolp3.github.io" # the base hostname & protocol for your site
twitter_username: fusepool
github_username:  fusepoolp3

# Build settings
markdown: kramdown

